### ISSUE TITLE
Build badge should report master status

### ISSUE THREAD

**Issue by JohnStrunk** [gluster/gluster-csi-driver#96]
**Describe the bug**
The "build:passing" badge in the main `README.md` points to the current centos-ci status for the driver. Unfortunately, it doesn't report on just the status of the master branch, it reports on the last CI job. This could have been a PR test that failed, and by reporting on the main page, it gives the impression that our repo master is broken.

**Steps to reproduce**

1. Submit a PR that fails centos-ci
1. Take a look at the badge in the main README for the repo

**Actual results**
Badge will show failed when master is fine

**Expected behavior**
Badge status should reflect master status

**Additional context**

**Comment by nixpanic** [comment]
It is trivial to add a job in the CentOS CI that runs the smoke tests on master every night. In order to reference it as a badge, the name of the job should be unique. That means a copy of the job in https://github.com/gluster/centosci/blob/master/jobs/csi-driver-smoke.yml (can be in the same file), with a trigger [`timed`](https://github.com/gluster/centosci/blob/master/jobs/nightly-rpm-builds.yml#L8).

Let me know if you need assistance with that, or if you want me to take care of it.

**Comment by JohnStrunk** [comment]
@nixpanic Thanks for jumping in.

What I'm really looking for is centos-ci to trigger on each merge to master (not nightly) and have the badge reflect the result. Travis does this, so I assume there's a way to get centos-ci to do it too.
(Alternatively, I can just switch the badge to point to Travis.)

**Comment by nixpanic** [comment]
Yes, that is possible as well. The [CentOS CI has the GitHub plugin enabled](https://wiki.centos.org/QaWiki/CI/GithubIntegration) and this can be used for that. The change I'm about to post for the centosci repository will need some testing, somehow...
